# Generated by Django 5.0.3 on 2024-04-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_author_image_homepage_summary"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_url",
            field=models.URLField(blank=True),
        ),
    ]
