# Generated by Django 5.0.3 on 2024-03-29 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FooterLinkers",
            new_name="FooterLinks",
        ),
    ]
